http:
  routers:
    baileys:
      rule: Host(`baileys.statuspersianas.com.br`) || Host(`baileys.ruptur.cloud`)
      entryPoints:
        - websecure
      service: baileys
      tls:
        certResolver: le
    ruptur-backend:
      rule: Host(`api.ruptur.cloud`) || Host(`webhook.ruptur.cloud`)
      entryPoints:
        - websecure
      service: ruptur-backend
      tls:
        certResolver: le
    ruptur-web:
      rule: Host(`app.ruptur.cloud`) || Host(`studio.ruptur.cloud`) || Host(`showcase.ruptur.cloud`) || Host(`site.ruptur.cloud`) || Host(`lp.ruptur.cloud`) || Host(`web.ruptur.cloud`) || Host(`ruptur.cloud`) || Host(`www.ruptur.cloud`)
      entryPoints:
        - websecure
      service: ruptur-web
      tls:
        certResolver: le
    app-warmup:
      rule: Host(`app.ruptur.cloud`) && PathPrefix(`/warmup`)
      entryPoints:
        - websecure
      middlewares:
        - warmup-strip
      service: warmup
      tls:
        certResolver: le

  middlewares:
    warmup-strip:
      stripPrefix:
        prefixes:
          - /warmup

  services:
    baileys:
      loadBalancer:
        servers:
          - url: http://baileys:3000
    ruptur-backend:
      loadBalancer:
        servers:
          - url: http://ruptur-backend:8000
    ruptur-web:
      loadBalancer:
        servers:
          - url: http://ruptur-web:3000
    warmup:
      loadBalancer:
        servers:
          - url: http://warmup:4173
