http:
  routers:
    baileys:
      rule: Host(`baileys.statuspersianas.com.br`) || Host(`baileys.ruptur.cloud`)
      entryPoints:
        - websecure
      service: baileys
      tls:
        certResolver: le
    ruptur-backend:
      rule: Host(`api.ruptur.cloud`) || Host(`webhook.ruptur.cloud`)
      entryPoints:
        - websecure
      service: ruptur-backend
      tls:
        certResolver: le

  services:
    baileys:
      loadBalancer:
        servers:
          - url: http://baileys:3000
    ruptur-backend:
      loadBalancer:
        servers:
          - url: http://ruptur-backend:8000
