http:
  routers:
    baileys:
      rule: Host(`baileys.ruptur.cloud`)
      entryPoints:
        - websecure
      service: baileys
      tls:
        certResolver: letsencrypt

    ruptur-backend:
      rule: Host(`api.ruptur.cloud`) || Host(`webhook.ruptur.cloud`)
      entryPoints:
        - websecure
      service: ruptur-backend
      tls:
        certResolver: letsencrypt

    ruptur-landing:
      rule: Host(`ruptur.cloud`) || Host(`www.ruptur.cloud`) || Host(`app.ruptur.cloud`)
      entryPoints:
        - websecure
      service: warmup
      tls:
        certResolver: letsencrypt

    app-warmup:
      priority: 3000
      rule: Host(`app.ruptur.cloud`) && PathPrefix(`/warmup`)
      entryPoints:
        - websecure
      middlewares:
        - warmup-strip
      service: warmup
      tls:
        certResolver: letsencrypt

  middlewares:
    warmup-strip:
      stripPrefix:
        prefixes:
          - /warmup

  services:
    ruptur-backend:
      loadBalancer:
        servers:
          - url: http://ruptur-backend:8000

    warmup:
      loadBalancer:
        servers:
          - url: http://warmup:4173
